###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
"name":"wilson Maldonado",
"usuario":"wilsonmv",
"contrasena":"wilson1234",
"email":"wsmaldonado90@gmail.com"
}


###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/6387ff5ab22c96d46cc9938a HTTP/1.1

###
PUT http://localhost:9000/api/users/6387ff5ab22c96d46cc9938a HTTP/1.1
Content-Type: application/json



{
"name":"Luis Eduardo Paez",
"usuario":"luisedupaez",
"contrasena":"luisedu3455",
"email":"luisedupaez03@gmail.com"
}

###
DELETE  http://localhost:9000/api/users/6387ff5ab22c96d46cc9938a
